# travis file for the broadbean package

language: python
python:
  - "3.5"

# be a good guy and potentially save time
cache: pip

# Don't receive notifications for now
notifications:
  email: false

branches:
  only:
    - master

install:
  - pip install --upgrade pip
  - pip install .

# command sequence to run tests
script:
  - cd tests
  - pytest

after_success:
  - cd ..
  - pip install -r docs_requirements.txt
  - cd docs
  - make -f Makefile gh-pages
